version: '3'

services:
    frontend:
      build: ./frontend
      ports:
        - 3000:3000
    training:
      build: ./training
      volumes:
        - models:/src/model
        - ./images:/src/imgs
    backend:
      build: ./backend
      volumes:
        - models:/src/model
      ports:
        - 5000:5000
volumes:
    models:
      